### PR TITLE
Implement random alt line

### PR DESCRIPTION
**Pull request by innovimax-jim**
remove deprecated method checkArguments
implement random alt line rule

### CODE REVIEW

**Comment by innovimax** [comment]
I added PMD
Here is the thing you have to fix
[INFO] PMD Failure: innovimax.mixthem.MixThem:211 Rule:UnusedLocalVariable Priority:3 Avoid unused local variables such as 'lineOrder'..
[INFO] PMD Failure: innovimax/mixthem/interfaces/IInputLine.java:4 Rule:UnusedImports Priority:4 Avoid unused imports such as 'java.io.UncheckedIOException'.
[INFO] PMD Failure: innovimax/mixthem/interfaces/IInputLine.java:5 Rule:UnusedImports Priority:4 Avoid unused imports such as 'java.util.stream.Stream'.
[INFO] PMD Failure: innovimax.mixthem.DefaultLineReader:69 Rule:UselessParentheses Priority:4 Useless parentheses..

**Comment by innovimax-jim** [comment]
Not streaming implemention removed

**Comment by innovimax-jim** [comment]
New implementation for alt-line rule using ReadType

**Comment by innovimax-jim** [comment]
Implementation for random-alt-line rule using ReadType done

**Comment by innovimax-jim** [comment]
@innovimax  a functional implementation instead of this switch implementation is planned later
as well as a modification in IInputLine.hasLine() that should return True only if there is a line to write regarding ReadType

**Pull request merged**
